# The MIT License (MIT)
# Maintaned Asociación Programo Ergo Sum
# - [@migueabellan](https://github.com/migueabellan)

# Build settings
markdown: kramdown
highlighter: rouge
#  input: GFM

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

theme: jekyll-theme-hacker


